### ISSUE TITLE
Dataset is not reachable

### ISSUE THREAD

**Issue by egedarici** [WeizhiXian/CGVQA#2]
Hi,

The link for the dataset is not reachable. Could you update the link please? It'd be of great help.  Thanks.

**Comment by WeizhiXian** [comment]
https://pan.baidu.com/s/1nOecZS7sYHdX8WclwNH7pQ?pwd=4567 
password:4567




| |
***@***.***
|
|
***@***.***
|




---- Replied Message ----
| From | Ege ***@***.***> |
| Date | 05/03/2023 15:55 |
| To | ***@***.***> |
| Cc | ***@***.***> |
| Subject | [WeizhiXian/CGVQA] Dataset is not reachable (Issue #2) |

Hi,

The link for the dataset is not reachable. Could you update the link please? It'd be of great help. Thanks.

**Comment by egedarici** [comment]
Thanks! I've figured I can reach the dataset using a VPN. Great work!
