### ISSUE TITLE
labels for the dataset

### ISSUE THREAD

**Issue by egedarici** [WeizhiXian/CGVQA#3]
Hi, where can I find the labels for the dataset? I need a labels.txt to work with.

**Comment by WeizhiXian** [comment]
MOS_Data.xlsx in the dataset https://pan.baidu.com/s/1nOecZS7sYHdX8WclwNH7pQ?pwd=4567



| |
***@***.***
|
|
***@***.***
|




---- Replied Message ----
| From | Ege ***@***.***> |
| Date | 05/16/2023 17:04 |
| To | ***@***.***> |
| Cc | ***@***.***> |
| Subject | [WeizhiXian/CGVQA] labels for the dataset (Issue #3) |

Hi, where can I find the labels for the dataset? I need a labels.txt to work with.
